n1 = input('digite algo:')
print('Este valor é {}'.format(type(n1)))
print('É alfabetico? {}'.format(n1.isalpha()))
print('É um espaço em branco? {}'.format(n1.isspace()))
print('É um número? {}'.format(n1.isnumeric()))
print('É alfanumerico? {}'.format(n1.isalnum()))
print('Está em maiuscula? {}'.format(n1.isupper()))
print('Está em minuscula? {}'.format(n1.islower()))
print('Está capitalisada? {}'.format(n1.istitle()))
